image: Visual Studio 2017

version: 0.6.0.{build}

skip_tags: true

skip_branch_with_pr: false

environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  _zip: '%APPVEYOR_BUILD_FOLDER%\ElDewrito-%APPVEYOR_BUILD_VERSION%.7z'
  _7z: 7z -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on a %_zip% -r -x!*.pdb -x!*.config

init:
  - git config --global core.autocrlf input

clone_folder: c:\projects\ElDorito

build_script:
- cmd: >-
    "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe" /nologo /m:2 /p:Configuration="Release" /p:Platform="Win32" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" "%APPVEYOR_BUILD_FOLDER%\ElDorito.sln"

before_build:
  - CD %APPVEYOR_BUILD_FOLDER%
  - MD ZIPPED
  - git clone https://github.com/scooterpsu/medalPack.git .\ZIPPED\mods\medals\default
  - echo D|xcopy /e /y %APPVEYOR_BUILD_FOLDER%\web .\ZIPPED\mods\ui\web
  - echo D|xcopy /e /y %APPVEYOR_BUILD_FOLDER%\libs\cef\artifact_extras .\ZIPPED
  - echo F|xcopy /y %APPVEYOR_BUILD_FOLDER%\dewrito.json .\ZIPPED

after_build:
- cmd: >-
    appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\Release\mtndew.dll

    echo F|xcopy /y %APPVEYOR_BUILD_FOLDER%\Release\CefProcess.exe .\ZIPPED\custom_menu.exe

    echo F|xcopy /y %APPVEYOR_BUILD_FOLDER%\Release\mtndew.dll .\ZIPPED

    echo F|xcopy /y %APPVEYOR_BUILD_FOLDER%\Release\mtndew.dll .\

    CD .\ZIPPED\

    %_7z% *

    CD ..

    appveyor PushArtifact %_zip%