version: 0.6.0.{build}
clone_folder: C:\Projects\ElDorito
init:
- cmd: git config --global core.autocrlf input
environment:
  _zip: '%APPVEYOR_BUILD_FOLDER%\ElDewrito-%APPVEYOR_BUILD_VERSION%.7z'
  _7z: 7z -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on a %_zip% -r -x!*.pdb -x!*.config
  _release: '"C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe" "ElDorito.vcxproj" /m /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=Release /p:Platform="x86"'
install:
- cmd: >-
    cinst cmake -version 3.2.3 -y

    cmake --version


    CD %APPVEYOR_BUILD_FOLDER%\

    mkdir build
    cd build
    IF EXIST "C:\Program Files (x86)\CMake\bin\" (
      "C:\Program Files (x86)\CMake\bin\cmake" -G "Visual Studio 12" --build ..
    ) ELSE (
      IF EXIST "C:\Program Files\CMake\bin\" (
        "C:\Program Files\CMake\bin\cmake" -G "Visual Studio 12" --build ..
      ) ELSE (
        cmake -G "Visual Studio 12" --build ..
      )
    )
build_script:
- cmd: >-
    CD %APPVEYOR_BUILD_FOLDER%\build\

    %_release%


    CD %APPVEYOR_BUILD_FOLDER%\build\Release\

    appveyor PushArtifact mtndew.dll


    %_7z% *.dll


    CD %APPVEYOR_BUILD_FOLDER%\

    %_7z% dewrito.json

    CD %APPVEYOR_BUILD_FOLDER%\libs\libwebsockets\bin\

    %_7z% *

    CD %APPVEYOR_BUILD_FOLDER%\libs\teamspeak\bin\

    %_7z% *

    CD %APPVEYOR_BUILD_FOLDER%\artifact_extras\

    %_7z% *

    appveyor PushArtifact %_zip%
