version: 0.6.0.{build}
clone_folder: C:\Projects\ElDorito
init:
- cmd: git config --global core.autocrlf input
environment:
  _zip: '%APPVEYOR_BUILD_FOLDER%\ElDewrito-%APPVEYOR_BUILD_VERSION%.7z'
  _7z: 7z -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on a %_zip% -r -x!*.pdb -x!*.config
  _release: '"C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe" "ElDorito.sln" /m /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=Release /p:Platform="Win32"'
install:
- cmd: >-
    cinst cmake -version 3.3.1 -y

    cmake --version

    CD %APPVEYOR_BUILD_FOLDER%\

    mkdir build

    cd build

    cmake -G "Visual Studio 12" --build ..

build_script:
- cmd: >-
    CD %APPVEYOR_BUILD_FOLDER%\build\

    %_release%

    appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\build\Release\mtndew.dll

    mkdir C:\ed

    git clone https://github.com/scooterpsu/medalPack.git C:\ed\mods\medals\default

    echo F|xcopy /y %APPVEYOR_BUILD_FOLDER%\build\Release\mtndew.dll C:\ed

    echo F|xcopy /y %APPVEYOR_BUILD_FOLDER%\build\Release\CefProcess.exe C:\ed\custom_menu.exe

    echo F|xcopy /y %APPVEYOR_BUILD_FOLDER%\dewrito.json C:\ed

    echo D|xcopy /e /y %APPVEYOR_BUILD_FOLDER%\libs\libwebsockets\bin C:\ed

    echo D|xcopy /e /y %APPVEYOR_BUILD_FOLDER%\libs\teamspeak\bin C:\ed

    echo D|xcopy /e /y %APPVEYOR_BUILD_FOLDER%\libs\cef\artifact_extras C:\ed

    echo D|xcopy /e /y %APPVEYOR_BUILD_FOLDER%\web C:\ed\mods\ui\web

    cd C:\ed

    %_7z% *

    appveyor PushArtifact %_zip%
